#!/bin/bash

DIR_NAME="my_dir"
LOG_FILE="logs.log"
PKG_IN="InstalledPkg.txt"

#Create File If not Exit
PATH_DIR="$(dirname $0)/$DIR_NAME"
if [[ ! -d $PATH_DIR ]]
then
	sudo mkdir $PATH_DIR
fi

LOG_FILE_PATH=$PATH_DIR/$LOG_FILE
if [[ ! -f $LOG_FILE_PATH ]]
then
	sudo touch $LOG_FILE_PATH
	sudo chmod 777 $LOG_FILE_PATH
fi

LIST_FILE_PATH=$PATH_DIR/$PKG_IN
if [[ ! -f $LIST_FILE_PATH ]]
then
	sudo touch $LIST_FILE_PATH
	sudo chmod 777 $LIST_FILE_PATH
fi


FILE=$LIST_FILE_PATH

echo -e  "Package Installation Utility\n"


#echo $FILE $LOG_FILE_PATH

#Insert Log function
InsertLog() {
	#$0 : Script_name
	#$1 : string
	echo -e "$(date +%D::%k:%M:%S) \"$1\"" >> $LOG_FILE_PATH 

}




#list All package
if [[ "$1" == "-l" ]]
then
	echo -e  "List of Installed Package :- \n"
	LIST=$(cat $FILE)
	if [[ -z $LIST  ]]
	then
		echo "No Result"
	else
		count=1
		cat $FILE | while read i
		do 
			if [[ -n  $i ]]
			then	
				echo -e "$count. $i"
			fi
			((count++))
		done
	fi
	InsertLog "listing pkg"
	exit 0
elif [[ "$1" == "-u" ]] || [[ "$1" == "remove" ]]
then
	echo "Uninstalling $2"
	RESULT=$(awk -F " " '{print $1}' $FILE | grep -w $2)
	if [[ "$?" ==  "1" ]]
       	then
		echo "Error : No package ($2) found"
		exit 0
	fi

	#Remove package name from List
	sudo apt remove $2 -y
	if [[ $? -ne 0 ]]
	then
		echo "Error : Something wrong while removing name from list"
		LogInsert "Error while remove $2"
	       	exit 0
	fi	
	ex +g/$2/d -cwq $FILE
	InsertLog "Removed $2"
elif [[ "$1" == "update" ]] 
then
	echo -e "GET [$date] : Updating and Upgrading System....\n\n "
	sudo apt update -y && sudo apt upgrade -y

	echo "Upgrading Done"
	InsertLog "Update&Upgrade"
elif [[ "$1" == "-h" ]] || [[ "$1" == "--help" ]]
then
	echo -e "Welcome To Get Installation Utility\n"
	echo -e "[ get  -l ] : Get List of Installed Package"
	echo -e "[ sudo get <Install Apps> ]"
	echo -e "[ sudo get -u[remove] <App> ]"
	echo -e "[ sudo get update ]"
	echo -e "[ --log ] : get logs details"
	echo -e "[ -h/--help ] : Help ]"
elif [[ "$1" == "--log" ]]
then
	cat $LOG_FILE_PATH
else
	for app in $@
	do 
		RES=$(grep -w $app $FILE)
		if [[ $? -eq 0 ]]
		then
			echo -e "GET : \"$app\" Already Installed <try \"get -l\">"
		else
			echo "Installing \"$app\""
			sudo apt install $app -y
			if [[ $? -eq 0 ]]
			then
				echo "$app $(date +%D::%X)" >> $FILE
				InsertLog "Installed $app"
			else
				echo "Error while downloading $app"
			fi
		fi
	done
fi
